import csv
import logging
import toml
from pathlib import Path
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field

from ..core.config import get_campaign_dir, load_campaign_config
from ..core.exclusions import ExclusionManager
from ..core.geocoding import (
    get_coordinates_from_address,
    get_coordinates_from_city_state,
)

logger = logging.getLogger(__name__)


class CampaignEditTargets(BaseModel):
    """Files a human editor may open for a campaign (config + optional README)."""

    campaign_name: str
    campaign_dir: Path
    config_path: Path
    readme_path: Path
    files_to_edit: List[Path] = Field(default_factory=list)
    config_exists: bool = False
    readme_exists: bool = False


class CampaignListItem(BaseModel):
    """Lightweight row for ``cocli campaign list`` (no full Campaign validation)."""

    name: str
    path: Path
    description: str = ""
    tag: Optional[str] = None
    domain: Optional[str] = None
    active: bool = False


def _readme_first_paragraph(readme_path: Path, *, max_len: int = 160) -> str:
    """First prose paragraph from a campaign README (skip headings/blanks)."""
    if not readme_path.is_file():
        return ""
    try:
        text = readme_path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""

    paragraphs: List[str] = []
    buf: List[str] = []
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped:
            if buf:
                paragraphs.append(" ".join(buf))
                buf = []
            continue
        if stripped.startswith("#"):
            if buf:
                paragraphs.append(" ".join(buf))
                buf = []
            continue
        buf.append(stripped)
    if buf:
        paragraphs.append(" ".join(buf))

    if not paragraphs:
        return ""
    desc = paragraphs[0]
    if len(desc) > max_len:
        return desc[: max_len - 1].rstrip() + "…"
    return desc


def _campaign_description_from_dir(campaign_dir: Path) -> tuple[str, Optional[str], Optional[str]]:
    """
    Resolve (description, tag, domain) without full Pydantic Campaign validation.

    Prefer ``[campaign].description`` in config.toml; else first README paragraph;
    else a short tag/domain summary.
    """
    tag: Optional[str] = None
    domain: Optional[str] = None
    config_desc = ""
    config_path = campaign_dir / "config.toml"
    if config_path.is_file():
        try:
            with open(config_path, "r", encoding="utf-8") as f:
                data = toml.load(f)
            section = data.get("campaign") or {}
            if isinstance(section, dict):
                raw_desc = section.get("description")
                if isinstance(raw_desc, str):
                    config_desc = raw_desc.strip()
                t = section.get("tag")
                d = section.get("domain")
                tag = t.strip() if isinstance(t, str) and t.strip() else None
                domain = d.strip() if isinstance(d, str) and d.strip() else None
        except Exception as e:
            logger.debug("Could not read campaign config %s: %s", config_path, e)

    if config_desc:
        return config_desc, tag, domain

    readme_desc = _readme_first_paragraph(campaign_dir / "README.md")
    if readme_desc:
        return readme_desc, tag, domain

    bits = [b for b in (tag, domain) if b]
    if bits:
        return " · ".join(bits), tag, domain
    return "", tag, domain


class CampaignService:
    def __init__(self, campaign_name: str):
        self.campaign_name = campaign_name
        self.campaign_dir = get_campaign_dir(campaign_name)
        if not self.campaign_dir:
            # Fallback for bootstrapping: check if the directory exists in data/campaigns
            from ..core.config import get_campaigns_dir

            self.campaign_dir = get_campaigns_dir() / campaign_name

        self.config_path = self.campaign_dir / "config.toml"
        self.exclusion_manager = ExclusionManager(campaign_name)

    def get_config(self) -> Dict[str, Any]:
        """Returns the raw configuration dictionary."""
        return load_campaign_config(self.campaign_name)

    def activate(self) -> None:
        """
        Sets this campaign as the active context and performs side effects 
        like updating .aws_profile.env with the campaign's AWS profile.
        """
        from ..core.config import set_campaign
        from pathlib import Path
        
        set_campaign(self.campaign_name)
        
        config = self.get_config()
        admin_profile = config.get("aws", {}).get("profile")
        
        if admin_profile:
            # POLICY: Use a gitignored local environment file for the profile
            env_file = Path(".aws_profile.env")
            try:
                content = f'# Generated by cocli campaign set {self.campaign_name}\n'
                content += f'export AWS_PROFILE="{admin_profile}"\n'
                with open(env_file, "w") as f:
                    f.write(content)
                logger.info(f"Updated .aws_profile.env with AWS_PROFILE={admin_profile}")
            except Exception as e:
                logger.warning(f"Could not update .aws_profile.env: {e}")

    def add_exclude(self, identifier: str, reason: Optional[str] = None) -> bool:
        """Identifier can be a slug or a domain."""
        if "." in identifier:
            self.exclusion_manager.add_exclusion(domain=identifier, reason=reason)
        else:
            self.exclusion_manager.add_exclusion(slug=identifier, reason=reason)
        return True

    def remove_exclude(self, identifier: str) -> bool:
        if "." in identifier:
            self.exclusion_manager.remove_exclusion(domain=identifier)
        else:
            self.exclusion_manager.remove_exclusion(slug=identifier)
        return True

    def add_query(self, query: str) -> bool:
        config = load_campaign_config(self.campaign_name)
        queries = config.setdefault("prospecting", {}).get("queries", [])
        if query not in queries:
            queries.append(query)
            queries.sort()
            config["prospecting"]["queries"] = queries
            self._save_config(config)
            return True
        return False

    def remove_query(self, query: str) -> bool:
        config = load_campaign_config(self.campaign_name)
        queries = config.get("prospecting", {}).get("queries", [])
        if query in queries:
            queries.remove(query)
            config["prospecting"]["queries"] = queries
            self._save_config(config)
            return True
        return False

    def add_location(self, location: str) -> bool:
        config = load_campaign_config(self.campaign_name)
        target_csv = config.get("prospecting", {}).get("target-locations-csv")
        
        if target_csv:
            csv_path = self.campaign_dir / target_csv
            rows = []
            exists = False
            fieldnames = ["name", "beds", "lat", "lon", "city", "state", "csv_name", "saturation_score", "company_slug"]
            
            if csv_path.exists():
                with open(csv_path, "r", newline="") as f:
                    reader = csv.DictReader(f)
                    if reader.fieldnames:
                        fieldnames = list(reader.fieldnames)
                    for row in reader:
                        if row.get("name") == location or row.get("city") == location:
                            exists = True
                        rows.append(row)
            
            if not exists:
                new_row = {fn: "" for fn in fieldnames}
                if "," in location:
                    city, state = [part.strip() for part in location.split(",", 1)]
                    new_row["city"] = city
                    new_row["state"] = state
                    new_row["name"] = location
                    coords = get_coordinates_from_city_state(location)
                else:
                    new_row["name"] = location
                    new_row["city"] = location
                    coords = get_coordinates_from_address(location)
                
                if coords:
                    new_row["lat"] = str(coords["latitude"])
                    new_row["lon"] = str(coords["longitude"])
                
                rows.append(new_row)
                rows.sort(key=lambda x: x.get("name") or x.get("city") or "")
                
                with open(csv_path, "w", newline="") as f:
                    writer = csv.DictWriter(f, fieldnames=fieldnames)
                    writer.writeheader()
                    writer.writerows(rows)
                return True
        else:
            locations = config.setdefault("prospecting", {}).get("locations", [])
            if location not in locations:
                locations.append(location)
                locations.sort()
                config["prospecting"]["locations"] = locations
                self._save_config(config)
                return True
        return False

    def remove_location(self, location: str) -> bool:
        config = load_campaign_config(self.campaign_name)
        target_csv = config.get("prospecting", {}).get("target-locations-csv")
        removed = False
        
        if target_csv:
            csv_path = self.campaign_dir / target_csv
            if csv_path.exists():
                rows = []
                with open(csv_path, "r", newline="") as f:
                    reader = csv.DictReader(f)
                    fieldnames = list(reader.fieldnames) if reader.fieldnames else []
                    for row in reader:
                        if row.get("name") == location or row.get("city") == location:
                            removed = True
                            continue
                        rows.append(row)
                
                if removed:
                    with open(csv_path, "w", newline="") as f:
                        writer = csv.DictWriter(f, fieldnames=fieldnames)
                        writer.writeheader()
                        writer.writerows(rows)
                    return True
        
        if not removed:
            locations = config.get("prospecting", {}).get("locations", [])
            if location in locations:
                locations.remove(location)
                config["prospecting"]["locations"] = locations
                self._save_config(config)
                return True
        return False

    def add_node(self, hostname: str, label: Optional[str] = None) -> bool:
        """Adds a worker node to the cluster configuration."""
        config = self.get_config()
        cluster = config.setdefault("cluster", {})
        nodes = cluster.setdefault("nodes", [])
        
        # Check if already exists
        for node in nodes:
            if node.get("host") == hostname:
                return False
                
        nodes.append({"host": hostname, "label": label or hostname})
        self.save_config(config)
        return True

    def remove_node(self, hostname: str) -> bool:
        """Removes a worker node from the cluster configuration."""
        config = self.get_config()
        cluster = config.get("cluster", {})
        nodes = cluster.get("nodes", [])
        
        initial_len = len(nodes)
        cluster["nodes"] = [n for n in nodes if n.get("host") != hostname]
        
        if len(cluster["nodes"]) < initial_len:
            self.save_config(config)
            return True
        return False

    def set_scaling(self, host: str, worker_type: str, count: int) -> bool:
        """Sets the worker count for a specific host and task type."""
        config = self.get_config()
        scaling = config.setdefault("prospecting", {}).setdefault("scaling", {})
        host_scaling = scaling.setdefault(host, {})
        host_scaling[worker_type] = count
        self.save_config(config)
        return True

    def geocode_locations(self) -> int:
        """
        Scans the campaign's target locations CSV and fills in missing geocoordinates.
        Returns the number of updated locations.
        """
        config = self.get_config()
        target_csv = config.get("prospecting", {}).get("target-locations-csv")
        if not target_csv:
            return 0

        csv_path = self.campaign_dir / target_csv
        if not csv_path.exists():
            return 0

        rows = []
        updated_count = 0
        fieldnames = []
        
        with open(csv_path, "r", newline="") as f:
            reader = csv.DictReader(f)
            fieldnames = list(reader.fieldnames) if reader.fieldnames else []
            for row in reader:
                if not row.get("lat") or not row.get("lon"):
                    name = row.get("name") or row.get("city")
                    if name:
                        coords = None
                        if "," in name:
                            coords = get_coordinates_from_city_state(name)
                        else:
                            coords = get_coordinates_from_address(name)
                        
                        if coords:
                            row["lat"] = str(coords["latitude"])
                            row["lon"] = str(coords["longitude"])
                            updated_count += 1
                rows.append(row)

        if updated_count > 0:
            with open(csv_path, "w", newline="") as f:
                writer = csv.DictWriter(f, fieldnames=fieldnames)
                writer.writeheader()
                writer.writerows(rows)
        
        return updated_count

    def save_config(self, config: Any) -> None:
        """
        Saves the campaign configuration.
        Accepts either a dictionary or a Campaign Pydantic model.
        """
        if hasattr(config, "model_dump"):
            # If it's a Pydantic model (like Campaign)
            data = config.model_dump(by_alias=True, exclude_none=True)
            
            # The Campaign model is flattened. We need to move campaign-specific 
            # fields back into a [campaign] section to match the established format.
            campaign_fields = ["name", "tag", "domain", "company-slug", "workflows", "queue_type", "timezone"]
            structured_data: Dict[str, Any] = {"campaign": {}}
            
            for k, v in data.items():
                if k in campaign_fields:
                    structured_data["campaign"][k] = v
                else:
                    structured_data[k] = v
            
            with open(self.config_path, "w") as f:
                toml.dump(structured_data, f)
        else:
            with open(self.config_path, "w") as f:
                toml.dump(config, f)
        logger.info(f"Saved configuration to {self.config_path}")

    def _save_config(self, config: Dict[str, Any]) -> None:
        self.save_config(config)

    def compile_lifecycle_index(self) -> Any:
        """
        Compiles the lifecycle index for this campaign.
        Yields progress updates.
        """
        from ..core.lifecycle_manager import LifecycleManager
        manager = LifecycleManager(self.campaign_name)
        yield from manager.compile()

    def restore_names_from_index(self, dry_run: bool = False) -> Any:
        """
        Reads from the Google Maps prospect index and restores names in _index.md.
        Also writes a file-per-object USV to enrichments/ for provenance.
        Yields status updates for progress bars.
        """
        from ..core.prospects_csv_manager import ProspectsIndexManager
        from ..models.companies.company import Company
        from ..core.config import get_companies_dir
        from ..models.campaigns.indexes.google_maps_prospect import GoogleMapsProspect

        manager = ProspectsIndexManager(self.campaign_name)
        companies_dir = get_companies_dir()
        
        stats = {"restored": 0, "receipts_written": 0, "errors": 0}
        
        # 1. Load prospects into a list to get a total count
        prospects = list(manager.read_all_prospects())
        total = len(prospects)
        
        for i, prospect in enumerate(prospects):
            if not prospect.company_slug or not prospect.name:
                continue
                
            slug = prospect.company_slug
            company_obj = Company.get(slug)
            
            # Yield progress
            yield {"current": i + 1, "total": total, "slug": slug}

            if not company_obj:
                continue

            try:
                # 1. Restore Name if corrupted or missing
                if company_obj.name != prospect.name:
                    logger.info(f"Restoring name for {slug}: {company_obj.name} -> {prospect.name}")
                    company_obj.name = prospect.name
                    if not dry_run:
                        company_obj.save(email_sync=False)
                    stats["restored"] += 1

                # 2. Write provenance receipt (google_maps.usv)
                if not dry_run:
                    enrich_dir = companies_dir / slug / "enrichments"
                    enrich_dir.mkdir(exist_ok=True)
                    receipt_path = enrich_dir / "google_maps.usv"
                    
                    from cocli.core.constants import UNIT_SEP
                    with open(receipt_path, "w", encoding="utf-8") as f:
                        header = UNIT_SEP.join(list(GoogleMapsProspect.model_fields.keys()))
                        f.write(f"{header}\n")
                        f.write(prospect.to_usv())
                    stats["receipts_written"] += 1
                    
            except Exception as e:
                logger.error(f"Failed to restore name for {slug}: {e}")
                stats["errors"] += 1
                
        yield stats

    # ------------------------------------------------------------------
    # Remaining mgmt surface (from commands/campaign/mgmt.py)
    # Intermediate artifacts: campaign config.toml, geocode cache (via add_location/geocode)
    # ------------------------------------------------------------------

    @staticmethod
    def list_campaign_names() -> List[str]:
        """Return campaign slugs (relative to campaigns root) under the data root."""
        from ..core.config import get_all_campaign_dirs, get_campaigns_dir

        root = get_campaigns_dir()
        names: List[str] = []
        for d in get_all_campaign_dirs():
            try:
                names.append(str(d.relative_to(root)))
            except ValueError:
                names.append(d.name)
        return names

    @staticmethod
    def list_campaigns() -> List[CampaignListItem]:
        """
        List local campaigns with descriptions for interactive CLI use.

        Fast path: pruned directory walk + light TOML/README reads only.
        Does not load full Campaign models (those can fail validation and are slow).
        """
        from ..core.config import get_all_campaign_dirs, get_campaign, get_campaigns_dir

        root = get_campaigns_dir()
        active = get_campaign()
        items: List[CampaignListItem] = []
        for campaign_dir in get_all_campaign_dirs():
            try:
                name = str(campaign_dir.relative_to(root))
            except ValueError:
                name = campaign_dir.name
            description, tag, domain = _campaign_description_from_dir(campaign_dir)
            items.append(
                CampaignListItem(
                    name=name,
                    path=campaign_dir,
                    description=description,
                    tag=tag,
                    domain=domain,
                    active=(name == active),
                )
            )
        return items

    @staticmethod
    def create_campaign(name: str, company: str) -> Path:
        """
        Bootstrap a new campaign under data_home.

        Returns the campaign directory path. Raises FileNotFoundError on missing
        templates (same as Campaign.create).
        """
        from ..core.config import get_cocli_base_dir
        from ..models.campaigns.campaign import Campaign

        data_home = get_cocli_base_dir()
        Campaign.create(name, company, data_home)
        return get_campaign_dir(name) or (data_home / "campaigns" / name)

    @staticmethod
    def clear_context() -> None:
        """Clear the active campaign context."""
        from ..core.config import set_campaign

        set_campaign(None)

    def get_edit_targets(self) -> CampaignEditTargets:
        """Resolve config.toml / README.md paths available for interactive edit."""
        if not self.campaign_dir or not self.campaign_dir.exists():
            raise FileNotFoundError(f"Campaign '{self.campaign_name}' not found.")

        config_path = self.campaign_dir / "config.toml"
        readme_path = self.campaign_dir / "README.md"
        files: List[Path] = []
        if config_path.exists():
            files.append(config_path)
        if readme_path.exists():
            files.append(readme_path)
        if not files:
            raise FileNotFoundError(
                f"No files to edit for campaign '{self.campaign_name}'."
            )
        return CampaignEditTargets(
            campaign_name=self.campaign_name,
            campaign_dir=self.campaign_dir,
            config_path=config_path,
            readme_path=readme_path,
            files_to_edit=files,
            config_exists=config_path.exists(),
            readme_exists=readme_path.exists(),
        )

    def load_campaign_model(self) -> Any:
        """
        Load and validate the campaign as a Campaign Pydantic model.

        Used by ``campaign show``. Raises FileNotFoundError / ValueError on bad config.
        """
        from ..models.campaigns.campaign import Campaign

        if not self.campaign_dir:
            raise FileNotFoundError(f"Campaign '{self.campaign_name}' not found.")
        if not self.config_path.exists():
            raise FileNotFoundError(
                f"Configuration file not found for campaign '{self.campaign_name}'."
            )

        with open(self.config_path, "r") as f:
            config_data = toml.load(f)

        flat_config = config_data.pop("campaign")
        flat_config.update(config_data)
        return Campaign.model_validate(flat_config)

    def get_s3_campaign_uri(self) -> str:
        """
        S3 URI root for this campaign's data layout.

        Prefer ``aws.data_bucket_name`` / ``aws.cocli_data_bucket_name``; fall back
        to ``cocli-data-{campaign}`` (matches original bucket command).
        """
        if not self.campaign_dir:
            raise FileNotFoundError(
                f"Campaign directory not found for {self.campaign_name}"
            )
        if not self.config_path.exists():
            raise FileNotFoundError(
                f"config.toml not found for {self.campaign_name}"
            )

        with open(self.config_path, "r") as f:
            config = toml.load(f)

        aws_config = config.get("aws", {})
        bucket_name = aws_config.get("data_bucket_name") or aws_config.get(
            "cocli_data_bucket_name"
        )
        if not bucket_name:
            bucket_name = f"cocli-data-{self.campaign_name}"
        return f"s3://{bucket_name}/campaigns/{self.campaign_name}/"
