from typing import Protocol, List, Dict, Any, Optional, Iterator, Callable, Set
from pathlib import Path
from cocli.models.search import SearchResult
from cocli.models.companies.meeting import CompanyMeeting
from cocli.models import TileStatusResult, MissionReconciliationResult
from cocli.models.tasks import MissionTask
from cocli.models.cli_help import CliCommandMatch


class SearchProvider(Protocol):
    def __call__(
        self,
        search_query: str = "",
        item_type: Optional[str] = None,
        campaign_name: Optional[str] = None,
        force_rebuild_cache: bool = False,
        filters: Optional[Dict[str, Any]] = None,
        sort_by: Optional[str] = None,
        limit: int = 100,
        offset: int = 0
    ) -> List[SearchResult]:
        ...

class CompanyServiceProvider(Protocol):
    def __call__(self, company_slug: str) -> Optional[Dict[str, Any]]:
        ...

class MeetingServiceProvider(Protocol):
    campaign_name: str
    def get_all_meetings(self) -> List[CompanyMeeting]:
        ...
    def get_upcoming_meetings(self) -> List[CompanyMeeting]:
        ...
    def get_recent_meetings(self, days_limit: int = 180) -> List[CompanyMeeting]:
        ...


class WebServiceProvider(Protocol):
    campaign_name: str
    def resolve_deployment_config(
        self,
        profile: Optional[str] = None,
        bucket_name: Optional[str] = None,
        domain: Optional[str] = None,
    ) -> Dict[str, str]:
        ...
    def fetch_cdk_outputs(self, profile: str) -> Dict[str, str]:
        ...
    def get_campaign_reports(self) -> Dict[str, Any]:
        ...
    def export_and_upload_emails_csv(
        self,
        s3_client: Any,
        bucket_name: str,
        log_callback: Optional[Callable[[str], None]] = None,
    ) -> Any:
        ...


class IndexServiceProvider(Protocol):
    campaign_name: str
    def get_status(self, index_name: str = "google_maps_prospects") -> Any: ...
    def list_interrupted_runs(
        self, index_name: str = "google_maps_prospects"
    ) -> List[str]: ...
    def recover_interrupted_run(
        self,
        index_name: str,
        run_id: str,
        log_file: Optional[Path] = None,
    ) -> None: ...
    def compact(
        self,
        index_name: str = "google_maps_prospects",
        log_file: Optional[Path] = None,
        log_callback: Optional[Callable[[str], None]] = None,
    ) -> Any: ...
    def trace_prospects(
        self, place_ids: List[str], index_name: str = "google_maps_prospects"
    ) -> Any: ...
    def discover_all_place_ids(self, index_name: str = "google_maps_prospects") -> List[str]: ...
    def requeue_stuck_details(
        self, place_ids: List[str], index_name: str = "google_maps_prospects"
    ) -> Any: ...
    def requeue_enrichment_gaps(self, place_ids: List[str]) -> Any: ...
    def requeue_missing_details(self, place_ids: List[str], batch_size: int = 1000) -> Any: ...
    def purge_invalid_place_ids(
        self, index_name: str = "google_maps_prospects", dry_run: bool = True
    ) -> Any: ...
    def clean_quote_corruption(
        self, index_name: str = "google_maps_prospects", dry_run: bool = True
    ) -> Any: ...
    def archive_incomplete_schema_wal(
        self,
        index_name: str = "google_maps_prospects",
        required_field_count: int = 57,
        dry_run: bool = True,
    ) -> Any: ...
    def backfill_domains(
        self,
        limit: int = 0,
        compact: bool = True,
        log_callback: Optional[Callable[[str], None]] = None,
    ) -> Any: ...
    def resolve_index_dir(
        self, index_name: str, campaign: Optional[str] = None
    ) -> Path: ...
    def write_datapackage(
        self,
        index_name: str,
        force: bool = False,
        campaign: Optional[str] = None,
    ) -> Any: ...


class TaskServiceProvider(Protocol):
    issues_root: Path
    def sync_index(self) -> int:
        ...
    def get_all_tasks(self) -> List[MissionTask]:
        ...
    def prioritize_task(self, slug: str, position: int) -> bool:
        ...
    def get_next_task(self) -> Optional[MissionTask]:
        ...
    def resolve_file(self, slug: str) -> Optional[Path]:
        ...
    def get_markdown_content_with_links(self, path: Path, seen: Optional[Set[Path]] = None) -> List[Dict[str, str]]:
        ...
    def start_task(self, slug: Optional[str] = None) -> Dict[str, Any]:
        ...
    def create_task(
        self,
        title: str,
        slug: Optional[str] = None,
        body: Optional[str] = None,
        draft: bool = False,
        depends_on: Optional[str] = None,
    ) -> Dict[str, Any]:
        ...
    def complete_task(
        self,
        slug: Optional[str] = None,
        commit_message: Optional[str] = None,
        commit_body: Optional[str] = None,
        commit_fn: Optional[Callable[[str, Optional[str]], None]] = None,
    ) -> Dict[str, Any]:
        ...


class TemplateCountsProvider(Protocol):
    def __call__(self, campaign_name: Optional[str] = None) -> Dict[str, int]:
        ...

class CampaignServiceProvider(Protocol):
    campaign_name: str
    def get_config(self) -> Dict[str, Any]: ...
    def activate(self) -> None: ...
    def add_exclude(self, identifier: str, reason: Optional[str] = None) -> bool: ...
    def remove_exclude(self, identifier: str) -> bool: ...
    def add_query(self, query: str) -> bool: ...
    def remove_query(self, query: str) -> bool: ...
    def add_location(self, location: str) -> bool: ...
    def remove_location(self, location: str) -> bool: ...
    def add_node(self, hostname: str, label: Optional[str] = None) -> bool: ...
    def remove_node(self, hostname: str) -> bool: ...
    def set_scaling(self, host: str, worker_type: str, count: int) -> bool: ...
    def geocode_locations(self) -> int: ...
    def save_config(self, config: Any) -> None: ...
    def compile_lifecycle_index(self) -> Iterator[Any]: ...
    def restore_names_from_index(self, dry_run: bool = False) -> Iterator[Any]: ...
    def get_edit_targets(self) -> Any: ...
    def load_campaign_model(self) -> Any: ...
    def get_s3_campaign_uri(self) -> str: ...

class WorkerServiceProvider(Protocol):
    campaign_name: str
    async def run_worker(self, headless: bool, debug: bool, workers: int, role: str) -> None: ...
    async def run_details_worker(self, headless: bool, debug: bool, workers: int, role: str) -> None: ...
    async def run_enrichment_worker(self, headless: bool, debug: bool, workers: int) -> None: ...
    async def run_orchestrated_workers(self, worker_defs: List[Any], headless: bool, debug: bool) -> None: ...
    async def run_supervisor(self, headless: bool, debug: bool, interval: int) -> None: ...
    async def get_cluster_health(self) -> List[Dict[str, Any]]: ...
    def resolve_worker_definitions(self, hostname: str, running_in_fargate: bool) -> List[Any]: ...

class ReportingServiceProvider(Protocol):
    campaign_name: str
    def get_environment_status(self) -> Dict[str, Any]: ...
    def get_campaign_stats(self, campaign_name: Optional[str] = None) -> Dict[str, Any]: ...
    async def get_cluster_health(self) -> List[Dict[str, Any]]: ...
    def get_index_stats(self, campaign_name: Optional[str] = None) -> Dict[str, Any]: ...
    def save_cached_report(self, campaign_name: str, report_type: str, data: Dict[str, Any]) -> None: ...
    def load_cached_report(self, campaign_name: str, report_type: str) -> Optional[Dict[str, Any]]: ...
    def get_email_analysis(self, campaign_name: Optional[str] = None) -> Dict[str, Any]: ...
    def generate_coverage_kml(self, campaign_name: Optional[str] = None) -> Any: ...
    def generate_legacy_scrapes_kml(self, campaign_name: Optional[str] = None) -> Any: ...
    def resolve_publish_config(
        self,
        profile: Optional[str] = None,
        bucket_name: Optional[str] = None,
        domain: Optional[str] = None,
        campaign_name: Optional[str] = None,
    ) -> Dict[str, str]: ...
    def generate_publish_kmls(
        self,
        campaign_name: Optional[str] = None,
        log_callback: Optional[Callable[[str], None]] = None,
    ) -> None: ...
    def upload_kml_layers(
        self,
        profile: str,
        bucket_name: str,
        domain: str,
        campaign_name: Optional[str] = None,
        log_callback: Optional[Callable[[str], None]] = None,
    ) -> Any: ...
    def publish_kml(
        self,
        profile: Optional[str] = None,
        bucket_name: Optional[str] = None,
        domain: Optional[str] = None,
        campaign_name: Optional[str] = None,
        log_callback: Optional[Callable[[str], None]] = None,
        generate: bool = True,
    ) -> Any: ...
    def place_kml_for_turboship(
        self,
        campaign_name: Optional[str] = None,
        turboship_kml_exports_path: Path = ...,
        kml_filename: str = "turboship_coverage.kml",
        kml_type: str = "customers",
    ) -> Any: ...
    def export_value_resources(self, campaign_name: Optional[str] = None) -> Any: ...

class AuditServiceProvider(Protocol):
    campaign_name: str
    def audit_campaign_integrity(self, fix: bool = False) -> Dict[str, Any]: ...
    def audit_queue_completion(self, execute: bool = False) -> Dict[str, Any]: ...
    def audit_cluster_paths(self, target_paths: List[str], campaigns: Optional[List[str]] = None) -> List[Dict[str, Any]]: ...
    def get_cli_tree(self, click_command: Any) -> str: ...
    def search_cli_tree(self, click_command: Any, query: str, limit: int = 25) -> List[CliCommandMatch]: ...
    def get_tui_actions(self, classes: List[type]) -> str: ...
    def get_tui_operations(self) -> str: ...
    def audit_filesystem(
        self,
        campaign_name: Optional[str] = None,
        skip_companies: bool = True,
        gen_cleanup: bool = False,
    ) -> Dict[str, Any]: ...
    def audit_schemas(
        self,
        campaign: Optional[str] = None,
        fix: bool = False,
        dry_run: bool = False,
    ) -> Dict[str, Any]: ...
    def run_queue_gm_list(self, campaign_name: str) -> str: ...
    def audit_enrichment(self, campaign_name: str) -> Dict[str, Any]: ...
    def get_enrichment_interactive_targets(self, campaign_name: str) -> List[tuple[Optional[str], str, str, bool, bool]]: ...
    def run_gm_list_html_audit(self, campaign: str, limit: int, output: str) -> Path: ...
    def prepare_validate(
        self,
        campaign: str,
        tile: Optional[str] = None,
        phrase: Optional[str] = None,
        usv_path: Optional[Path] = None,
        headed: bool = False,
        limit: int = 0,
    ) -> Dict[str, Any]: ...
    def save_reviewed_item(self, reviewed_path: Path, place_id: str, field_name: str, expected: str) -> None: ...
    def replay_audit_corrections(
        self,
        campaign: str,
        usv_path: Path,
        output: Optional[Path] = None,
        corrections_path: Optional[Path] = None,
        reviewed_path_opt: Optional[Path] = None,
    ) -> Dict[str, Any]: ...
    def export_cases(self, campaign: str, tile: Optional[str] = None, phrase: Optional[str] = None) -> Dict[str, Any]: ...
    def get_tile_status(self, campaign_name: str) -> TileStatusResult: ...
    def audit_mission_reconciliation(self, campaign_name: str) -> MissionReconciliationResult: ...
    def purge_leases(self, campaign_name: str, queue_name: str, force: bool = False, dry_run: bool = False, max_age_minutes: int = 30) -> Dict[str, Any]: ...

class AuditCodebaseServiceProvider(AuditServiceProvider, Protocol):
    """Subset of AuditService focusing on codebase operations."""
    # Inherits methods from AuditServiceProvider; can be further restricted if needed.
    ...

class AuditQueueServiceProvider(AuditServiceProvider, Protocol):
    """Subset of AuditService focusing on queue‑related operations."""
    # Inherits methods from AuditServiceProvider; can be further restricted.
    ...

class AuditClusterServiceProvider(AuditServiceProvider, Protocol):
    """Subset of AuditService focusing on cluster‑path operations."""
    # Inherits methods from AuditServiceProvider; can be further restricted.
    ...

class DataSyncServiceProvider(Protocol):
    campaign_name: str
    def sync_prospects(self, force: bool = False, full: bool = False) -> Dict[str, Any]: ...
    def sync_companies(self, force: bool = False, full: bool = False) -> Dict[str, Any]: ...
    def sync_emails(self, force: bool = False, full: bool = False) -> Dict[str, Any]: ...
    def sync_indexes(self, force: bool = False, full: bool = False) -> Dict[str, Any]: ...
    def sync_queues(self, queue_name: Optional[str] = None, force: bool = False, full: bool = False) -> Dict[str, Any]: ...
    def sync_all(self, force: bool = False, full: bool = False) -> Dict[str, Any]: ...
    def compact_index(self) -> Dict[str, Any]: ...
    def push_queue(self, queue_name: str = "enrichment") -> Dict[str, Any]: ...
    def list_datapackages(self) -> List[Any]: ...
    def describe_schema(self, file_path: Path) -> Any: ...
    def locate_datapackage(self, file_path: Path) -> Optional[Path]: ...
    def sample_rows(
        self,
        file_path: Path,
        limit: int = 10,
        resource_name: Optional[str] = None,
    ) -> Any: ...
    def compute_metrics(
        self,
        file_path: Path,
        resource_name: Optional[str] = None,
        output_path: Optional[Path] = None,
    ) -> Any: ...
    def search_usv(
        self,
        file_path: Path,
        query: str,
        columns: str = "slug, phone, reviews_count",
    ) -> Any: ...
    def inspect_row(self, file_path: Path, row_number: int = 1) -> Any: ...
    def compact_queue(
        self, queue_name: str, campaign_name: Optional[str] = None
    ) -> Any: ...

class DeploymentServiceProvider(Protocol):
    campaign_name: str
    def scale_service(self, count: int) -> Dict[str, Any]: ...
    def deploy_infra(self) -> Dict[str, Any]: ...
    def get_service_status(self) -> Dict[str, Any]: ...
    def get_batch_status(self, campaign_name: Optional[str] = None) -> Any: ...
    def get_pi_stats(self, campaign_name: Optional[str] = None) -> Dict[str, Any]: ...
    def get_rollout_diagnostics(self, campaign_name: Optional[str] = None) -> Any: ...
    def broadcast_scaling_config(
        self,
        campaign_name: Optional[str] = None,
        log_callback: Optional[Callable[[str], None]] = None,
    ) -> Any: ...
    def push_config_to_s3(self, campaign_name: Optional[str] = None) -> Any: ...
    def pull_config_from_s3(self, campaign_name: Optional[str] = None) -> Any: ...
    def sync_rollout_results(
        self,
        campaign_name: Optional[str] = None,
        workers: int = 20,
        full: bool = False,
        force: bool = False,
        log_callback: Optional[Callable[[str], None]] = None,
    ) -> Any: ...
    async def push_discovery_data(self, delete: bool = False) -> None: ...
    async def sync_and_audit_cluster(self) -> None: ...

class EventServiceProvider(Protocol):
    campaign_name: str
    def get_pending_events(self) -> List[Any]: ...
    def approve_event(self, event: Any) -> bool: ...
    def reject_event(self, event: Any, reason: str = "") -> bool: ...
    def update_event(self, event: Any) -> bool: ...

class OperationServiceProvider(Protocol):
    campaign_name: str
    def get_details(self, op_id: str) -> Optional[Any]: ...
    def list_operations(self) -> List[Any]: ...
    async def execute(
        self, 
        op_id: str, 
        log_callback: Optional[Callable[[str], None]] = None,
        step_callback: Optional[Callable[[str, str], None]] = None,
        params: Optional[Dict[str, Any]] = None
    ) -> Dict[str, Any]: ...

class SecretServiceProvider(Protocol):
    def get_secret(self, key: str) -> Optional[str]: ...
    def get_item(self, item_id: str) -> Optional[Dict[str, Any]]: ...



