from typing import Protocol, List, Dict, Any, Optional, Iterator, Callable
from cocli.models.search import SearchResult

class SearchProvider(Protocol):
    def __call__(
        self,
        search_query: str = "",
        item_type: Optional[str] = None,
        campaign_name: Optional[str] = None,
        force_rebuild_cache: bool = False,
        filters: Optional[Dict[str, Any]] = None,
        sort_by: Optional[str] = None,
        limit: int = 100,
        offset: int = 0
    ) -> List[SearchResult]:
        ...

class CompanyServiceProvider(Protocol):
    def __call__(self, company_slug: str) -> Optional[Dict[str, Any]]:
        ...

class TemplateCountsProvider(Protocol):
    def __call__(self, campaign_name: Optional[str] = None) -> Dict[str, int]:
        ...

class CampaignServiceProvider(Protocol):
    campaign_name: str
    def get_config(self) -> Dict[str, Any]: ...
    def activate(self) -> None: ...
    def add_exclude(self, identifier: str, reason: Optional[str] = None) -> bool: ...
    def remove_exclude(self, identifier: str) -> bool: ...
    def add_query(self, query: str) -> bool: ...
    def remove_query(self, query: str) -> bool: ...
    def add_location(self, location: str) -> bool: ...
    def remove_location(self, location: str) -> bool: ...
    def add_node(self, hostname: str, label: Optional[str] = None) -> bool: ...
    def remove_node(self, hostname: str) -> bool: ...
    def set_scaling(self, host: str, worker_type: str, count: int) -> bool: ...
    def geocode_locations(self) -> int: ...
    def save_config(self, config: Any) -> None: ...
    def compile_lifecycle_index(self) -> Iterator[Any]: ...
    def restore_names_from_index(self, dry_run: bool = False) -> Iterator[Any]: ...

class WorkerServiceProvider(Protocol):
    campaign_name: str
    async def run_worker(self, headless: bool, debug: bool, workers: int, role: str) -> None: ...
    async def run_details_worker(self, headless: bool, debug: bool, workers: int, role: str) -> None: ...
    async def run_enrichment_worker(self, headless: bool, debug: bool, workers: int) -> None: ...
    async def run_orchestrated_workers(self, worker_defs: List[Any], headless: bool, debug: bool) -> None: ...
    async def run_supervisor(self, headless: bool, debug: bool, interval: int) -> None: ...
    async def get_cluster_health(self) -> List[Dict[str, Any]]: ...

class ReportingServiceProvider(Protocol):
    campaign_name: str
    def get_environment_status(self) -> Dict[str, Any]: ...
    def get_campaign_stats(self, campaign_name: Optional[str] = None) -> Dict[str, Any]: ...
    async def get_cluster_health(self) -> List[Dict[str, Any]]: ...
    def get_index_stats(self, campaign_name: Optional[str] = None) -> Dict[str, Any]: ...
    def save_cached_report(self, campaign_name: str, report_type: str, data: Dict[str, Any]) -> None: ...
    def load_cached_report(self, campaign_name: str, report_type: str) -> Optional[Dict[str, Any]]: ...
    def get_email_analysis(self, campaign_name: Optional[str] = None) -> Dict[str, Any]: ...

class AuditServiceProvider(Protocol):
    campaign_name: str
    def audit_campaign_integrity(self, fix: bool = False) -> Dict[str, Any]: ...
    def audit_queue_completion(self, execute: bool = False) -> Dict[str, Any]: ...
    def audit_cluster_paths(self, target_paths: List[str], campaigns: Optional[List[str]] = None) -> List[Dict[str, Any]]: ...

class DataSyncServiceProvider(Protocol):
    campaign_name: str
    def sync_prospects(self, force: bool = False, full: bool = False) -> Dict[str, Any]: ...
    def sync_companies(self, force: bool = False, full: bool = False) -> Dict[str, Any]: ...
    def sync_emails(self, force: bool = False, full: bool = False) -> Dict[str, Any]: ...
    def sync_indexes(self, force: bool = False, full: bool = False) -> Dict[str, Any]: ...
    def sync_queues(self, queue_name: Optional[str] = None, force: bool = False, full: bool = False) -> Dict[str, Any]: ...
    def sync_all(self, force: bool = False, full: bool = False) -> Dict[str, Any]: ...
    def compact_index(self) -> Dict[str, Any]: ...
    def push_queue(self, queue_name: str = "enrichment") -> Dict[str, Any]: ...

class DeploymentServiceProvider(Protocol):
    campaign_name: str
    def scale_service(self, desired_count: int) -> Dict[str, Any]: ...

class OperationServiceProvider(Protocol):
    campaign_name: str
    def get_details(self, op_id: str) -> Optional[Any]: ...
    async def execute(
        self, 
        op_id: str, 
        log_callback: Optional[Callable[[str], None]] = None,
        step_callback: Optional[Callable[[str, str], None]] = None,
        params: Optional[Dict[str, Any]] = None
    ) -> Dict[str, Any]: ...
