[campaign]
name = "roadmap"
tag = "roadmap"

[google_maps]
email = "treeluvburdpu@gmail.com"
one_password_path = "op://Private/gmail.com_treeluvburdpu/password"

[prospecting]
locations = [
  "Memphis, Tn",
  "Jackson, MS",
  "Atlanta, GA",
  "San Francisco, CA"
    ]
queries = ["wealth manager", "financial analyst", "pacific life"]
