[campaign]
name = "Turboship Q3 2025"
tag = "turboship"

[google_maps]
email = "admin@turboheatweldingtools.com"
one_password_path = "op://TurboHeatWelding/GMail_TurboHeatWeldingTools/password"

[prospecting]
locations = [
  "Memphis, Tn",
  "Jackson, MS"
    ]
queries = ["commercial vinyl flooring contractor", "rubber flooring contractor", "sports flooring contractor"]
