[campaign]
name = "Turboship Q3 2025"
tag = "turboship"

[google_maps]
email = "admin@turboheatweldingtools.com"
one_password_path = "op://TurboHeatWelding/GMail_TurboHeatWeldingTools/password"

[prospecting]
locations = ["Albuquerque, NM", "Las Vegas, NV", "Reno, NV", "Oxnard, CA", "Bakersfield, CA", "Santa Barbara, CA", "San Luis Obispo, CA", "Santa Cruz, CA"]
queries = ["commercial vinyl flooring contractor", "rubber flooring contractor", "sports flooring contractor"]
