[campaign]
name = "turboship"
tag = "turboship"

[google_maps]
email = "admin@turboheatweldingtools.com"
one_password_path = "op://TurboHeatWelding/GMail_TurboHeatWeldingTools/password"

[prospecting]
locations = [
  "Albuquerque, NM"
    ]
queries = ["commercial vinyl flooring contractor", "rubber flooring contractor", "sports flooring contractor"]
