import typer
import csv
import json
from rich.console import Console
from rich.progress import track
from typing import Optional
from pathlib import Path

from cocli.core.config import get_campaign
from cocli.core.queue.factory import get_queue_manager
from cocli.models.queue import QueueMessage
from cocli.models.company import Company

app = typer.Typer()
console = Console()

@app.command()
def main(
    csv_input: Path = typer.Argument(..., help="Path to input CSV file generated by list_prospects_missing_emails.py"),
    campaign_name: Optional[str] = typer.Option(None, "--campaign", "-c", help="Campaign name. Defaults to current context."),
    limit: int = typer.Option(100, "--limit", "-l", help="Number of prospects to re-scrape. Set to 0 for all."),
    tag: str = typer.Option("batch-v6-full", "--tag", "-t", help="Tag to apply to selected prospects."),
) -> None:
    """
    Reads prospects from a CSV, tags them, and enqueues them for re-scraping.
    """
    if not campaign_name:
        campaign_name = get_campaign()
    
    if not campaign_name:
        console.print("[bold red]Error: No campaign specified and no active context.[/bold red]")
        raise typer.Exit(1)

    if not csv_input.exists():
        console.print(f"[bold red]Error: CSV file not found: {csv_input}[/bold red]")
        raise typer.Exit(1)

    # 1. Read from CSV
    targets = []
    with open(csv_input, "r") as f:
        reader = csv.DictReader(f)
        for row in reader:
            targets.append(row)
            if limit > 0 and len(targets) >= limit:
                break

    if not targets:
        console.print("[yellow]No targets found in CSV.[/yellow]")
        return

    console.print(f"Selected [bold green]{len(targets)}[/bold green] targets from CSV.")

    # 2. Tag, Save, and Enqueue
    queue_manager = get_queue_manager("enrichment", use_cloud=True, campaign_name=campaign_name)
    enqueued_data = []

    for target in track(targets, description="Processing targets..."):
        slug = target["slug"]
        domain = target["domain"]
        
        # Load actual company object to tag it
        company = Company.get(slug)
        if not company:
            console.print(f"[yellow]Warning: Could not load company with slug {slug}. Skipping tag.[/yellow]")
        else:
            if tag not in company.tags:
                company.tags.append(tag)
                company.save()

        # Enqueue with force_refresh
        msg = QueueMessage(
            domain=domain,
            company_slug=slug,
            campaign_name=campaign_name,
            force_refresh=True, 
            ttl_days=30,
            ack_token=None,
        )
        queue_manager.push(msg)
        enqueued_data.append(target)

    # 3. Save reference file for these 100
    output_path = Path(f"enqueued_{tag}.json")
    output_path.write_text(json.dumps(enqueued_data, indent=2))
    
    console.print(f"\n[bold green]Success![/bold green]")
    console.print(f"Tagged and enqueued {len(enqueued_data)} prospects from CSV.")
    console.print(f"Enqueued reference saved to: [bold]{output_path}[/bold]")

if __name__ == "__main__":
    app()
