#!/usr/bin/env python3
import subprocess
from pathlib import Path

def install_hooks() -> None:
    """Installs a pre-commit hook that runs 'make test'."""
    try:
        # Get the hooks directory
        result = subprocess.run(
            ["git", "rev-parse", "--git-path", "hooks"],
            capture_output=True,
            text=True,
            check=True
        )
        hooks_dir = Path(result.stdout.strip())
        
        pre_commit_path = hooks_dir / "pre-commit"
        
        hook_content = """#!/bin/bash
# Pre-commit hook to ensure tests pass before committing.
# Generated by scripts/install_hooks.py

echo "Running pre-commit tests..."
make test
RESULT=$?

if [ $RESULT -ne 0 ]; then
    echo "Error: Tests failed. Commit aborted."
    exit 1
fi

exit 0
"""
        
        pre_commit_path.write_text(hook_content)
        pre_commit_path.chmod(0o755)
        print(f"Successfully installed pre-commit hook at {pre_commit_path}")
        
    except Exception as e:
        print(f"Failed to install git hooks: {e}")

if __name__ == "__main__":
    install_hooks()
