from typing import Protocol, TypeVar, Any, List
from cocli.core.ordinant import StateFolder

T = TypeVar("T")

class CampaignQueueProtocol(Protocol[T]):
    campaign_name: str
    queue_name: str

    def push(self, task: T) -> Any: ...
    def poll(self, batch_size: int = 1) -> List[T]: ...
    def ack(self, task: T) -> None: ...
    def nack(self, task: T, is_http_500: bool = False) -> None: ...
    def count_state(self, state: StateFolder) -> int: ...